### ISSUE TITLE
Landsatのデータをレポジトリに含める

### ISSUE THREAD

**Issue by yutannihilation** [tsukubar/r-spatial-guide#2]
>  There are no restrictions on Landsat data downloaded from the USGS; it can be used or redistributed as desired. (https://www.usgs.gov/faqs/are-there-any-restrictions-use-or-redistribution-landsat-data)

とのことなので、可能であればレポジトリにデータを含められないかと思ったのですがどうでしょう。どのみち多くの人はUSGSにアカウント登録をすることになるのかもしれませんが、初心者は登録があると尻込みしてしまうのでもったいない気がしました（私は登録を尻込み中です...）。

あと、たぶん探し慣れてないせいだと思うんですけど、EarthExplorerでこのデータを見つけることができませんでした。。

https://github.com/tsukubar/r-spatial-guide/blob/0845bc07ca25b3828924ab5094f0cb6728062989/raster.Rmd#L54
https://github.com/tsukubar/r-spatial-guide/blob/0845bc07ca25b3828924ab5094f0cb6728062989/raster.Rmd#L59

**Comment by uribo** [comment]
助言くださり、ありがとうございます。

やや記憶が消えていますが、こちらのラスタ ファイルは AWSのサービスからダウンロードしたファイルを利用していました。
https://landsatonaws.com/L8/107/035/LC08_L1TP_107035_20180814_20180814_01_RT

リポジトリにデータを含めるで気がかかりなのは一ファイルで60MB程度あるので
リポジトリの肥大化が不安です。

なので[Geocomputation with R](https://geocompr.robinlovelace.net/)や[Spatial Data Science](https://keen-swartz-3146c4.netlify.com/)のように
spDataLargeなど既存パッケージのデータセットを使うのが良いのかな思っています。

**Comment by yutannihilation** [comment]
あー、なるほど。AWSの方だったんですね。それなら登録しなくても入手できるし、レポジトリに含めるにはデカすぎるので今のままで良いと思います（既存パッケージのデータセットで済めばいいけど、やっぱり日本周辺のデータを使いたいとなると無理そうだし）。情報あざす！
